name: Java Test and Publish

on: [push]

jobs:
  build:
    environment: database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run Maven Tests
        run: mvn test
        env:
          GH_DB_HOST: ${{ secrets.GH_DB_HOST }}
          GH_DB_PORT: ${{ secrets.GH_DB_PORT }}
          GH_DB_DATABASE: ${{ secrets.GH_DB_DATABASE }}
          GH_DB_SCHEMA: ${{ secrets.GH_DB_SCHEMA }}
          GH_DB_USER: ${{ secrets.GH_DB_USER }}
          GH_DB_PASSWD: ${{ secrets.GH_DB_PASSWD }}
          GH_DB_TABLE: ${{ secrets.GH_DB_TABLE }}
      - name: Build and publish package
        run: |
          mvn -B versions:set -DnewVersion=$GITHUB_SHA -DgenerateBackupPoms=false
          mvn -B -DskipTests -Dskip.installnodenpm -Dskip.npm -Pskip-shaded-web-jar -Pskip-tools-jar source:jar deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
